### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by valschmidt** [rolker/AutonomousMissionPlanner#1]
Converting the BSB to tiff using gdalwarp fixed any projection issues. 

Here's a list of feature requests or minor fixes in nor order but as they occur to me:

Calculate distance between points in a trackline and cumulative distance. Give ability to specify speed (and to specify a default).  Calculate time to complete the trackline.

For survey patterns, after the first click, display the lat/lon of first point and update the heading and length of the first line in real-time. After the second click display and update the distance of the second dimension of the pattern, the distance between successive lines, the cumulative distance of the entire pattern, and given a default speed the time to compete the pattern. After the survey pattern is drawn, display all these parameters allowing modification of any of them. 

Add the ability to reorder items in a mission, moving them up or down relative to the others. 

For a mission, calculate the total distance for the entire mission, including transits between entities, and total time given default or specified speeds.

The ability to add multiple backgrounds, adjust the layering of their display and transparency. 

I suppose the menus could be re-arranged such that one creates and configures one or more platforms under the platform menu and then for any given platform creates one or missions. Then mission elements could be added under each mission created. 

Buttons for adding each mission element. 

Ability to select multiple mission elements (or a whole mission) and move them wholesale. 

In the "survey pattern" tool, there's a small bug in which one cannot get a line to end at a point without inadvertently drawing the follow-on transit stub. 

A measuring tool showing distance and bearing. 

I did a series of clicks to specify a survey pattern which caused everything to crash. It was a east-to-west click at the same latitude followed by a third click above them. 

I think that's it. 
-val

**Comment by rolker** [comment]
Thanks for the feedback. I've just opened a bunch of requests for the individual items. Feel free to comment or add details to any of them.
