### ISSUE TITLE
Some files are missing

### ISSUE THREAD

**Issue by shujaatak** [rolker/AutonomousMissionPlanner#29]
The project does not have subfolders and files:
```
geographic_msgs/GeoPointStamped.h
ros/ros.h
std_msgs/Bool.h
std_msgs/String.h
```
The application does not compile without them:

`C:\Qt_Workspace\AutonomousMissionPlanner\rosnode.h:6: error: C1083: Cannot open include file: 'geographic_msgs/GeoPointStamped.h': No such file or directory
`

**Comment by rolker** [comment]
Those files don't belong in the project, they are ROS files. I will check to make sure that they don't get included when ROS is not selected in the CMake configuration. Thanks for pointing out this issue.

**Comment by shujaatak** [comment]
I don't know why rosnode and rosnodedetails get included in my project due to which I get those same errors. 

`C:\Qt_Workspace\AutonomousMissionPlanner\rosnode.h:6: error: C1083: Cannot open include file: 'geographic_msgs/GeoPointStamped.h': No such file or directory`

An alternative solutions to be:
Either entirely remove rosnode and rosnodedetails from the project as they are not needed 
OR
ifdef'ed out the whole source inside their respective files.

**Comment by rolker** [comment]
If you don't have the AMP_USE_ROS cmake variable set to true, those files shouldn't get included in the build according to the CMakeLists.txt file. Entirely removing them from the project is not an option as they are necessary for the optional ROS functionality.

**Comment by shujaatak** [comment]
In the console, I get this error while opening a background:

`ERROR 6: Unable to load PROJ.4 library (proj.dll), creation of OGRCoordinateTransformation failed.`

**Comment by lixingsuo** [comment]
CMake Error at CMakeLists.txt:29 (find_package):
By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "catkin", but
CMake did not find one.

Could not find a package configuration file provided by "catkin" with any
of the following names:

catkinConfig.cmake
catkin-config.cmake
Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
"catkin_DIR" to a directory containing one of the above files. If "catkin"
provides a separate development package or SDK, be sure it has been
installed.
Configuring incomplete, errors occurred!
See also "D:/AutonomousMissionPlanner-master/build/CMakeFiles/CMakeOutput.log".

above Error ,i don't know how to select "catkin_DIR"?
