### ISSUE TITLE
Unable to load PROJ.4 library

### ISSUE THREAD

**Issue by shujaatak** [rolker/AutonomousMissionPlanner#30]
In the console, I get this error while opening a background:

`ERROR 6: Unable to load PROJ.4 library (proj.dll), creation of OGRCoordinateTransformation failed.`

**Comment by rolker** [comment]
This is on Windows I presume? I normally develop on Linux (currently Ubuntu 17.04) but I have tested building and running on Windows 10 a while ago. I documented loosely how I did it in the README.md file. Does your environment match what I have documented there? Particularly, which version of GDAL are you using and how was it built and installed? You error message seems to suggest that GDAL is having a problem loading the proj4 library's DLL.

**Comment by shujaatak** [comment]
No worries, I solved it.
It would be much appreciable if you include the following "Building PROJ4" instructions in your reademe file:

Building PROJ4

- Download PROJ4 - https://github.com/OSGeo/proj.4
- Unzip it.
- In the source directory, edit nmake.opt modifiying INSTDIR to desired install/build location
- Run "VS2015 x64 Native Tools Command Prompt" for VS 2015
- Change directory to PROJ4 source directory
- Run these commands one after other:
1. - nmake /f makefile.vc MSVC_VER=1910 WIN64=1
2. - nmake /f makefile.vc MSVC_VER=1910 WIN64=1 install-all
- After completion, you will find the compiled PROJ4 lib, include and bin folders in your specified install/build location, From bin folder, copy proj.dll to the AutonomousMissionPlanner.exe folder. Done!
